int main(int argc, char** argv);
game_state* spawn_gs(game_state* par);
void free_gs(game_state* gs, field* save);
void cur_gs(game_state* gs);
int field_fish(field f);
int curp(game_state* gs);
void set_curp(game_state* gs, int p);
int pens_left(game_state* gs, int p);
void* gen_gs(void* arg);
game_state* parse_gs(char* in);
void print_gs(game_state* gs);
void print_move(move m);
game_state* qpop(void);
void qpush(game_state* gs);
void qempty(void);
